In [8]:
import numpy as np

In [9]:
first_trial_run = [10,23,12,17]

In [10]:
second_trial_run = [12,29,19,24]

In [11]:
np_first_trial_run = np.array(first_trial_run)

In [12]:
np_second_trial_run = np.array(second_trial_run)

In [13]:
np_first_trial_run + np_second_trial_run

array([22, 52, 31, 41])

In [14]:
#addition
np.add(23,34)

57

In [15]:
#subtraction
np.subtract(45,34)

11

In [17]:
#multiplication- create an array for daily hours
#15USD per hour - calculate wage

np_daily_wage = np.array([5,7,6,9])*15
np_daily_wage

array([ 75, 105,  90, 135])

In [19]:
#sum of daily wage =  weekly wage
np_weekly_wage = np.sum(np_daily_wage)
np_weekly_wage

405

In [23]:
#comparison operators
np_weekly_hours = np.array([23,45,43,34,25])
np_weekly_hours[np_weekly_hours>40]


array([45, 43])

In [24]:
np_weekly_hours[np_weekly_hours!=40]

array([23, 45, 43, 34, 25])

In [25]:
np.logical_and(np_weekly_hours>30,np_weekly_hours<50)

array([False,  True,  True,  True, False])

In [26]:
np.logical_not(np_weekly_hours>35)

array([ True, False, False,  True,  True])

In [82]:
np_fruits = np.array(['apple','orange','jack fruit','mango','papaya'])
np_fruits

array(['apple', 'orange', 'jack fruit', 'mango', 'papaya'], dtype='<U10')

In [83]:
np_fruit_copy = np_fruits
np_fruit_copy

array(['apple', 'orange', 'jack fruit', 'mango', 'papaya'], dtype='<U10')

In [84]:
np_fruits[1]

'orange'

In [85]:
np_fruit_copy[1]

'orange'

In [93]:
np_fruit_copy[1] = 'watermelon'
np_fruit_copy

array(['apple', 'watermelon', 'jack fruit', 'mango', 'papaya'],
      dtype='<U10')

In [94]:
np_fruit_copy

array(['apple', 'watermelon', 'jack fruit', 'mango', 'papaya'],
      dtype='<U10')

In [90]:
np_fruits[1] = 'cherry'

In [95]:
np_fruits

array(['apple', 'watermelon', 'jack fruit', 'mango', 'papaya'],
      dtype='<U10')

In [92]:
np_fruit_copy

array(['apple', 'cherry', 'jack fruit', 'mango', 'papaya'], dtype='<U10')

In [99]:
print(id(np_fruits))

3062481752272


In [100]:
print(id(np_fruit_copy))

3062481752272


In [101]:
np_cars = np.array(['nexon','harrier','tiago','hexa'])
np_cars

array(['nexon', 'harrier', 'tiago', 'hexa'], dtype='<U7')

In [103]:
np_cars_copy = np_cars.view()
np_cars_copy

array(['nexon', 'harrier', 'tiago', 'hexa'], dtype='<U7')

In [115]:
print(id(np_cars))

3062481908560


In [116]:
print(id(np_cars_copy))

3062481910000


In [117]:
np_cars_copy[2]

'tiago'

In [118]:
np_cars_copy[2] = 'buzzard'
np_cars_copy

array(['nexon', 'harrier', 'buzzard', 'hexa'], dtype='<U7')

In [119]:
np_cars

array(['nexon', 'harrier', 'buzzard', 'hexa'], dtype='<U7')

In [112]:
np_cars[2] = 'tiago'
np_cars

array(['nexon', 'harrier', 'tiago', 'hexa'], dtype='<U7')

In [114]:
np_cars_copy

array(['nexon', 'harrier', 'tiago', 'hexa'], dtype='<U7')

In [120]:
np_animals = np.array(['dog','cat','tiger','lion'])
np_animals

array(['dog', 'cat', 'tiger', 'lion'], dtype='<U5')

In [121]:
np_animals_copy = np_animals.copy()
np_animals_copy

array(['dog', 'cat', 'tiger', 'lion'], dtype='<U5')

In [122]:
print(id(np_animals))

3062481765840


In [123]:
print(id(np_animals_copy))

3062481765760


In [125]:
np_animals[1] = 'rat'
np_animals

array(['dog', 'rat', 'tiger', 'lion'], dtype='<U5')

In [126]:
np_animals_copy

array(['dog', 'cat', 'tiger', 'lion'], dtype='<U5')

In [128]:
np_animals_copy[2] = 'hippo'
np_animals_copy

array(['dog', 'cat', 'hippo', 'lion'], dtype='<U5')

In [130]:
np_animals

array(['dog', 'rat', 'tiger', 'lion'], dtype='<U5')