In [3]:
import numpy as np

In [7]:
np_sqrt = np.sqrt([2,3,4,5,6,7,8,9])
np_sqrt

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        ])

In [8]:
from numpy import pi

In [9]:
np.cos(0)

1.0

In [11]:
np.sin(pi/2)

1.0

In [12]:
np.cos(pi)

-1.0

In [13]:
np.floor([1.2,1.6,2.4,2.9,9.8,9.2])

array([1., 1., 2., 2., 9., 9.])

In [15]:
np.ceil(np.exp([1,2,3,4]))

array([ 3.,  8., 21., 55.])

In [16]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [17]:
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [28]:
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [20]:
new_cyclist_trials.reshape(2,6)


array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [22]:
new_cyclist_trials.resize(2,6)

In [29]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [30]:
np.hsplit(new_cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]), array([[26, 13, 19],
        [24, 14, 23]])]

In [32]:
np_cyclist_1 = np.array([23,45,32,53])


In [31]:
np_cyclist_2 = np.array([24,53,32,43])

In [34]:
np.hstack((np_cyclist_1,np_cyclist_2))

array([23, 45, 32, 53, 24, 53, 32, 43])