In [1]:
import numpy as np
from scipy import linalg

In [2]:
test_rating = np.array([[5,8],[7,9]])

In [3]:
eigenValues, eigenVector = linalg.eig(test_rating)

In [4]:
eigenValues

array([-0.74596669+0.j, 14.74596669+0.j])

In [5]:
first_eigen, second_eigen = eigenValues

In [6]:
eigenVector

array([[-0.81220939, -0.63447346],
       [ 0.58336601, -0.77294465]])

In [7]:
first_eig_vec = eigenVector[:,0]

In [8]:
first_eig_vec

array([-0.81220939,  0.58336601])

In [9]:
second_eig_vec = eigenVector[:,1]