In [1]:
from scipy import linalg
import numpy as np

In [3]:
matrix = np.array([[2,9],[5,8]])
matrix

array([[2, 9],
       [5, 8]])

In [4]:
matrix.ndim

2

In [5]:
type(matrix)

numpy.ndarray

In [6]:
linalg.inv(matrix)

#calculate inverse of a matrix

array([[-0.27586207,  0.31034483],
       [ 0.17241379, -0.06896552]])

In [7]:
linalg.det(matrix)

#calculate the determinant of a matrix

-29.0

Solve the given linear equations

2x+3y+z = 21
-x+5y+4z = 9
3x+2y+9z = 6

In [8]:
numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [9]:
numArrValue = np.array([21,9,6])

In [10]:
linalg.solve(numArray,numArrValue)

array([ 4.95,  4.35, -1.95])

Single Value Decomposition SVD

In [11]:
numSvdArr = np.array([[3,5,1],[9,5,7]])

In [12]:
linalg.svd(numSvdArr)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))